interface Params {
    "isBpg2": "true",
    "reviewsCount": "10",
    "reviewsRating": "5",
    "merchantCountBpg2": "3",
    "cashback": "6",
    "PriceNotGLC": "7097",
    "LT_cluster1": "1",
    "LT_cluster2": "1",
    "LT_cluster3": "1",
    "installment": "true",
    "Высота профиля, в процентах": "55",
    "Ширина профиля, в миллиметрах": "205",
    "Диаметр, в дюймах": "16",
    "Назначение": "для легкового автомобиля",
    "favorite_offer_merchant": "12400",
    "is_item_increased_cashback": "false",
    "merchants": "9381, 13732, 15825, 13181, 19166, 17427, 17754"
}

interface Item {
    "OldPrice": number,
    "Price": number,
    "Weight": number,
    "ItemId": number,
    "CategoryIds": number[],
    "CategoryPathsToRoot": number[][],
    "Regions": null,
    "CategoryNames": string[],
    "Params": Params,
    "GroupId": string,
    "StockId": null,
    "Size": null,
    "Color": null,
    "Algorithm": string,
    "BuyUrl": null,
    "Vendor": string,
    "Description": string,
    "TypePrefix": null,
    "Model": string,
    "Url": string,
    "PictureUrl": string,
    "Name": string
}